In [52]:
def rm_ele(rm_ls,ls):
    return [i for num, i in enumerate(ls) if num not in rm_ls]

from ase.io import read

filename = "/home/jyb/lyt/bpdc_0.xyz"
center_atom = 'O' # the center atoms must be the only 

poly = read(filename)

sym_ls, pos_arr = poly.get_chemical_symbols(), poly.get_positions()
pos_ls = [list(i) for i in pos_arr]
ind = -1
for i in range(len(sym_ls)):
    if sym_ls[i] == center_atom:
        ind = i
if ind < 0: raise ValueError("wrong centered atom")
sym_ls.pop(ind); ref_coor = pos_ls.pop(ind)

# maybe you can remove H atom to reduce problems
removed_atom = 'H'
rm_ls = []
for i in range(len(sym_ls)):
    if sym_ls[i] == 'H':
        rm_ls.append(i)

sym_ls = rm_ele(rm_ls,sym_ls)
pos_ls = rm_ele(rm_ls,pos_ls)

elem_dic = dict(zip(sym_ls,pos_ls))
elem_ls = elem_dic.keys()
elem_dic = dict(zip(elem_ls,range(0,len(elem_ls))))
symbol_ls = [elem_dic[i] for i in sym_ls]
coor_ls = [[x-y for x,y in zip(ref_coor,ls)] for ls in pos_ls]

[[i] + j for i, j in zip(sym_ls,coor_ls)]

[['O', -6.82957, 9.141020000000001, -1.8559099999999997],
 ['O', -5.654669999999999, 9.79419, 0.0],
 ['C', -5.955979999999999, 8.947370000000001, -0.9279500000000009],
 ['C', -5.41875, 6.736780000000001, -1.9570600000000002],
 ['C', -4.38218, 7.330870000000001, 0.13634000000000057],
 ['N', -3.70282, 6.114800000000001, 0.14953000000000038],
 ['N', -4.74034, 5.519080000000001, -1.9526699999999995],
 ['C', -5.24346, 7.657450000000001, -0.9191599999999998],
 ['C', -3.8572699999999998, 5.174440000000001, -0.9015699999999995],
 ['O', -1.1531, -0.6909199999999984, -1.8559099999999997],
 ['C', -0.8840100000000002, 0.16247000000000256, -0.9279500000000009],
 ['C', -2.52982, 1.7330199999999998, -1.9570600000000002],
 ['C', -1.49705, 2.333660000000002, 0.13634000000000057],
 ['N', -2.21051, 3.5300400000000014, 0.14953000000000038],
 ['N', -3.2451799999999995, 2.9293900000000015, -1.9526699999999995],
 ['C', -1.6448600000000002, 1.4244900000000023, -0.9191599999999998],
 ['C', -3.1021099999999997,

In [42]:
'''
this matrix satisfy the property that (x,y,z) = D*(x,y,z)' () stands for a colume vector
'''
import numpy as np
def get_cartesian_to_fractional_matrix(a, b, c, alpha, beta, gamma,
                                       angle_in_degrees=True):
    """
    Return the transformation matrix that converts cartesian coordinates to
    fractional coordinates.
    Parameters
    ----------
    a, b, c : float
        The lengths of the edges.
    alpha, gamma, beta : float
        The angles between the sides.
    angle_in_degrees : bool
        True if alpha, beta and gamma are expressed in degrees.
    Returns
    -------
    r : array_like
        The 3x3 rotation matrix. ``V_frac = np.dot(r, V_cart)``.
    """
    if angle_in_degrees:
        alpha = np.deg2rad(alpha)
        beta = np.deg2rad(beta)
        gamma = np.deg2rad(gamma)
    cosa = np.cos(alpha)
    sina = np.sin(alpha)
    cosb = np.cos(beta)
    sinb = np.sin(beta)
    cosg = np.cos(gamma)
    sing = np.sin(gamma)
    volume = 1.0 - cosa**2.0 - cosb**2.0 - cosg**2.0 + 2.0 * cosa * cosb * cosg
    volume = np.sqrt(volume)
    r = np.zeros((3, 3))
    r[0, 0] = 1.0 / a
    r[0, 1] = -cosg / (a * sing)
    r[0, 2] = (cosa * cosg - cosb) / (a * volume * sing)
    r[1, 1] = 1.0 / (b * sing)
    r[1, 2] = (cosb * cosg - cosa) / (b * volume * sing)
    r[2, 2] = sing / (c * volume)
    return r

def get_fractional_to_cartesian_matrix(a, b, c, alpha, beta, gamma,
                                       angle_in_degrees=True):
    """
    Return the transformation matrix that converts fractional coordinates to
    cartesian coordinates.
    Parameters
    ----------
    a, b, c : float
        The lengths of the edges.
    alpha, gamma, beta : float
        The angles between the sides.
    angle_in_degrees : bool
        True if alpha, beta and gamma are expressed in degrees.
    Returns
    -------
    r : array_like
        The 3x3 rotation matrix. ``V_cart = np.dot(r, V_frac)``.
    """
    if angle_in_degrees:
        alpha = np.deg2rad(alpha)
        beta = np.deg2rad(beta)
        gamma = np.deg2rad(gamma)
    cosa = np.cos(alpha)
    sina = np.sin(alpha)
    cosb = np.cos(beta)
    sinb = np.sin(beta)
    cosg = np.cos(gamma)
    sing = np.sin(gamma)
    volume = 1.0 - cosa**2.0 - cosb**2.0 - cosg**2.0 + 2.0 * cosa * cosb * cosg
    volume = np.sqrt(volume)
    r = np.zeros((3, 3))
    r[0, 0] = a
    r[0, 1] = b * cosg
    r[0, 2] = c * cosb
    r[1, 1] = b * sing
    r[1, 2] = c * (cosa - cosb * cosg) / sing
    r[2, 2] = c * volume / sing
    return r

In [57]:
tuple(1,2,2)

TypeError: tuple() takes at most 1 argument (3 given)

In [55]:
a = get_cartesian_to_fractional_matrix(50,50,50,80,70,90)
b = DCM_rotation(85,75,68)

In [50]:
a = np.array([[3,4],[1,2]])
b = np.array([[3.7,4.5],[1.3,2.6]])

In [56]:
print(np.dot(a,b))
print(np.dot(b,a))

[[ 0.00760574 -0.00767998  0.0183857 ]
 [ 0.00878916  0.01759419  0.00522851]
 [-0.02091861  0.00519698  0.00209972]]
[[ 0.00045115 -0.0059025   0.02162892]
 [ 0.00515668  0.01849664  0.00066867]
 [-0.01931852  0.00479946  0.00835185]]


In [43]:
def symmetry_op(h,k,l,number):
    if number >= 207:
        ls_hkl = [
            [h,k,l],[-h,k,l],[h,-k,l],[h,k,-l],[-h,-k,l],[h,-k,-l],[-h,k,-l],[-h,-k,-l],
            [k,h,l],[-k,h,l],[k,-h,l],[k,h,-l],[-k,-h,l],[k,-h,-l],[-k,h,-l],[-k,-h,-l],
            [l,k,h],[-l,k,h],[l,-k,h],[l,k,-h],[-l,-k,h],[l,-k,-h],[-l,k,-h],[-l,-k,-h],
            [k,l,h],[-k,l,h],[k,-l,h],[k,l,-h],[-k,-l,h],[k,-l,-h],[-k,l,-h],[-k,-l,-h],
            [l,h,k],[-l,h,k],[l,-h,k],[l,h,-k],[-l,-h,k],[l,-h,-k],[-l,h,-k],[-l,-h,-k],
            [h,l,k],[-h,l,k],[h,-l,k],[h,l,-k],[-h,-l,k],[h,-l,-k],[-h,l,-k],[-h,-l,-k]
        ]
        set_hkl = {tuple(x) for x in ls_hkl}
        mutil = len(set_hkl)
    elif 206 >=number >=195:
        ls_hkl = [
            [h,k,l],[-h,k,l],[h,-k,l],[h,k,-l],[-h,-k,l],[h,-k,-l],[-h,k,-l],[-h,-k,-l],
	    [l,h,k],[-l,h,k],[l,-h,k],[l,h,-k],[-l,-h,k],[l,-h,-k],[-l,h,-k],[-l,-h,-k],
        [k,l,h],[-k,l,h],[k,-l,h],[k,l,-h],[-k,-l,h],[k,-l,-h],[-k,l,-h],[-k,-l,-h]
        ]
        set_hkl = {tuple(x) for x in ls_hkl}
        mutil = len(set_hkl)
    elif 142 >=number >=75:
        ls_hkl = [
            [h,k,l],[-h,k,l],[h,-k,l],[h,k,-l],[-h,-k,l],[h,-k,-l],[-h,k,-l],[-h,-k,-l],
            [k,h,l],[-k,h,l],[k,-h,l],[k,h,-l],[-k,-h,l],[k,-h,-l],[-k,h,-l],[-k,-h,-l],
        ]
        set_hkl = {tuple(x) for x in ls_hkl}
        mutil = len(set_hkl)
    elif 74 >=number >= 16:
        ls_hkl = [
            [h,k,l],[-h,k,l],[h,-k,l],[h,k,-l],[-h,-k,l],[h,-k,-l],[-h,k,-l],[-h,-k,-l]
        ]
        set_hkl = {tuple(x) for x in ls_hkl}
        mutil = len(set_hkl)
    elif number <=2 or number:
        ls_hkl = [[h,k,l]]
        set_hkl = {tuple(x) for x in ls_hkl}
        mutil = len(set_hkl)
    else:
        ls_hkl = [[h,k,l]]
        set_hkl = {tuple(x) for x in ls_hkl}
        mutil = len(set_hkl)
    return [h,k,l,mutil], set_hkl

In [44]:
ls_valid,set_hkl = symmetry_op(0,1,3,197)

In [45]:
set_hkl

{(-3, 0, -1),
 (-3, 0, 1),
 (-1, -3, 0),
 (-1, 3, 0),
 (0, -1, -3),
 (0, -1, 3),
 (0, 1, -3),
 (0, 1, 3),
 (1, -3, 0),
 (1, 3, 0),
 (3, 0, -1),
 (3, 0, 1)}

In [46]:
def hkl_compute(abc,wyck):
    # this is the number of space group
    try:
        number = int(wyck)
    except:
        number = int(wyck[:-1])
    
    H=int(abc[0]*2/1.54*0.42)
    K=int(abc[1]*2/1.54*0.42)
    L=int(abc[2]*2/1.54*0.42)
    cryst_face_0 = []
    cryst_face = []
    # ignore -h,-k,-l the mutil is doule
    for h in range(0,H+1):
        for k in range(0,K+1):
            for l in range(0,L+1):
                cryst_face_0.append((h,k,l))
                cryst_face.append((h,k,l))
    cryst_face.pop(0)# in order to remove (0,0,0)
    cryst_face_0.pop(0)
    # the line is to be removed
    hkl_val = []
    for h, k, l in cryst_face:
        if (h,k,l) not in cryst_face: continue
        #ls_valid,set_hkl = symmetry_op(h,k,l,number), I will change later
        ls_valid,set_hkl = symmetry_op(h,k,l,number)
        hkl_val.append(ls_valid)
        for each in set_hkl:
            try:
                cryst_face.remove(each)
            except:
                continue
    return hkl_val, [number]

def theta_filt(hkl_val,P,angle_min,angle_max,w=1.5406):
    a,b,c,aerfa,beta,gama = P[0], P[1], P[2], P[3]*np.pi/180, P[4]*np.pi/180, P[5]*np.pi/180
    V=a*b*c*np.sqrt(1-np.cos(aerfa)**2-np.cos(beta)**2-np.cos(gama)**2+2*np.cos(aerfa)*np.cos(beta)*np.cos(gama))
    hkl_val_new = []
    for h,k,l,mutil in hkl_val:
        t1=((h**2)*(b**2)*(c**2)*(np.sin(aerfa)**2)+(k**2)*(a**2)*(c**2)*(np.sin(beta)**2)+(l**2)*(a**2)*(b**2)*(np.sin(gama)**2)+2*h*k*a*b*(c**2)*(np.cos(aerfa)*np.cos(beta)-np.cos(gama))+2*k*l*(a**2)*b*c*(np.cos(beta)*np.cos(gama)-np.cos(aerfa))+2*h*l*a*(b**2)*c*(np.cos(aerfa)*np.cos(gama)-np.cos(beta)))
        double_theta = np.arcsin(np.sqrt(t1/(V**2))*1.54/2)*360/np.pi
        if angle_min < double_theta < angle_max: hkl_val_new.append([h,k,l,mutil,double_theta])
    return hkl_val_new

In [47]:
a, b = hkl_compute([50.84,50.84,50.84],"197")

In [49]:
P = [50.84,50.84,50.84]+[90,90,90]
k = theta_filt(a,P,4.0,29.8)
print(len(k))

732


In [39]:
for i in k:
    if i[0] == 0 and i[1]==1 and i[2]==3: print(i)

[0, 1, 3, 12, 5.490400022184282]


In [50]:
for i in k:
    if abs(i[-1]-5.49)<0.005:
        print(i)

[1, 3, 0, 12, 5.490400022184282]
[3, 1, 0, 12, 5.490400022184282]


In [35]:
P = [50.84,50.84,50.84]+[90,90,90]
k = theta_filt(a,P,3.0,30.0)
print(len(k))

881


In [24]:
for i in a:
    if i[0] == 1 and i[1]==2 and i[2] == 3:
        print(i)

In [33]:
print(len(a_1),len(a))

3345 6578


In [13]:
a_1, b_1 = hkl_compute([50.84,50.84,50.84],"207")

In [12]:
for i in a:
    if i[0]==3 and i[-1]==12: print(i)

[3, 5, 0, 12]
[3, 6, 0, 12]
[3, 7, 0, 12]
[3, 9, 0, 12]
[3, 11, 0, 12]
[3, 12, 0, 12]
[3, 13, 0, 12]
[3, 15, 0, 12]
[3, 17, 0, 12]
[3, 19, 0, 12]
[3, 20, 0, 12]
[3, 21, 0, 12]
[3, 23, 0, 12]
[3, 25, 0, 12]
[3, 27, 0, 12]


In [11]:
print(len(a))

6578


In [45]:
def DCM_rotation(alpha,beta,gamma,angle_in_degrees=True):
    '''
        input: alpha,beta,gama
        output: R*(x,y,z),return R
    '''
    if angle_in_degrees:
        alpha = np.deg2rad(alpha)
        beta = np.deg2rad(beta)
        gamma = np.deg2rad(gamma)
    cosa = np.cos(alpha)
    sina = np.sin(alpha)
    cosb = np.cos(beta)
    sinb = np.sin(beta)
    cosg = np.cos(gamma)
    sing = np.sin(gamma)
    
    return np.array([
                [cosa*cosb, cosa*sinb*sing-sina*cosg, cosa*sinb*cosg+sina*sing],
                [sina*cosb, sina*sinb*sing+cosa*cosg, sina*sinb*cosg-cosa*sing],
                [-sinb, cosb*sing, cosb*cosg]
            ])
    

In [101]:
def comb_scan(s):
    my_match(r"([^0-9]+[0-9]+)+$", s, "malformed Wyckoff combination")
    ret = [[x, int(n)] for x, n in re.findall(r"([^0-9]+)([0-9]+)", s)]
    if len(set(x for x, n in ret)) != len(ret):
        raise ValueError("duplicate position in Wyckoff combination")
    return ret

def at_scan(s):
    m = my_match(r"([^@]+)@([^@]+)$", s, "malformed `@'-expression").groups()
    return [int(m[0]), comb_scan(m[1])]

In [30]:
a = {"C":2,"D":4,"E":3}

In [37]:
sorted([[num,ele] for ele,num in a.items()])

[[2, 'C'], [3, 'E'], [4, 'D']]

In [35]:
import operator
sorted(a.items(),key=operator.itemgetter(1))

[('C', 2), ('E', 3), ('D', 4)]

In [104]:
def my_match(pat, s, err):
    ret = re.match(pat, s)
    if not ret:
        raise SyntaxError(err)
    return ret

In [127]:
"A-B".split("-")

['A', 'B']

In [125]:
my_match(".*L", "Ru3L", "malformed centered atoms with a ligand")

<_sre.SRE_Match object; span=(0, 4), match='Ru3L'>

In [25]:
import re
def check_ligand(ls):
    '''
        input: cr[elems][0],cr[elems][1]
        output: check whether Ru3+-L1 exists and add this extra_elems
    '''
    ret = []
    for i in range(len(ls)):
        for j in range(len(ls[i])):
            if re.search("-", ls[i][j][1]):
                new_ele = ls[i][j][1].split("-")
                ret.append([j,new_ele[1]])
                ls[i][j][1] = new_ele[0]
    return ret

In [29]:
a = [[[1.0, 'Yb3+']], [[1.0, 'Yb3+'],[1.0, 'Ru3+-ret']]]
print(check_ligand(a))
print(a)

[[1, 'ret']]
[[[1.0, 'Yb3+']], [[1.0, 'Yb3+'], [1.0, 'Ru3+']]]


In [103]:
at_scan("1@a5")

[1, [['a', 5]]]

In [1]:
import ase

In [85]:
a = sorted([v, k] for k, v in d.items())

In [89]:
a= [k for v, k in sorted([v, k] for k, v in d.items())]

In [82]:
from fractions import Fraction
[Fraction(0)] * 4

[Fraction(0, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)]

In [91]:
import re
def term_scan(s):
    m, ret = re.match(r"([+-]?[0-9/]*)([xyz]?)$", s).groups(), [Fraction(0)] * 4
    ret[{"x": 0, "y": 1, "z": 2, "": 3}.get(m[1])] = \
        Fraction(m[0] + "1" if m[0] in ["", "+", "-"] else m[0])
    return ret

def aff_add(a1, a2):
    ret = [x + y for x, y in zip(a1, a2)]
    return ret
def aff_scan(s):
    aff = [Fraction(0)] * 4
    for t in re.findall(r"[+-]?[^+-]+", s):
        aff = aff_add(aff, term_scan(t))
    return aff

In [93]:
def aff_comp(aff):
    lin = [list(a) for a in enumerate(aff[:3]) if a[1]]
    return [len(lin), aff[3], lin]

In [96]:
for i in a:
    print(i,aff_scan(i),aff_comp(aff_scan(i)))

x [Fraction(1, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)] [1, Fraction(0, 1), [[0, Fraction(1, 1)]]]
y [Fraction(0, 1), Fraction(1, 1), Fraction(0, 1), Fraction(0, 1)] [1, Fraction(0, 1), [[1, Fraction(1, 1)]]]
z [Fraction(0, 1), Fraction(0, 1), Fraction(1, 1), Fraction(0, 1)] [1, Fraction(0, 1), [[2, Fraction(1, 1)]]]
1/2-x [Fraction(-1, 1), Fraction(0, 1), Fraction(0, 1), Fraction(1, 2)] [1, Fraction(1, 2), [[0, Fraction(-1, 1)]]]
-y [Fraction(0, 1), Fraction(-1, 1), Fraction(0, 1), Fraction(0, 1)] [1, Fraction(0, 1), [[1, Fraction(-1, 1)]]]
1/2+z [Fraction(0, 1), Fraction(0, 1), Fraction(1, 1), Fraction(1, 2)] [1, Fraction(1, 2), [[2, Fraction(1, 1)]]]
-x [Fraction(-1, 1), Fraction(0, 1), Fraction(0, 1), Fraction(0, 1)] [1, Fraction(0, 1), [[0, Fraction(-1, 1)]]]
1/2+y [Fraction(0, 1), Fraction(1, 1), Fraction(0, 1), Fraction(1, 2)] [1, Fraction(1, 2), [[1, Fraction(1, 1)]]]
1/2-z [Fraction(0, 1), Fraction(0, 1), Fraction(-1, 1), Fraction(1, 2)] [1, Fraction(1, 2), [[2, Fra

In [77]:
d = {'x': 0, 'y': 1, 'z': 2, '1/2-x': 3, '-y': 4, '1/2+z': 5, '-x': 6, '1/2+y': 7, '1/2-z': 8, '1/2+x': 9, '1/2-y': 10, '-z': 11}
sorted([v, k] for k, v in d.items())

[[0, 'x'],
 [1, 'y'],
 [2, 'z'],
 [3, '1/2-x'],
 [4, '-y'],
 [5, '1/2+z'],
 [6, '-x'],
 [7, '1/2+y'],
 [8, '1/2-z'],
 [9, '1/2+x'],
 [10, '1/2-y'],
 [11, '-z']]

In [2]:
import numpy as np

In [3]:
from ase.io import read, write

In [64]:
from ase import Atoms

In [66]:
poly.symbols

Symbols('C5HCHC3H2CHCHC2H2N2C3O2C6NCHNCHCRuHCH2N4HC10HC2HC2HC2HC2HC2HC2HC2HNHNHNHNHC9HCHCHCHCH2CH2C7HCHCHCHCH2CH2C2O4')

In [68]:
poly.positions

array([[ 7.30983, 21.2823 , 30.32205],
       [ 8.55066, 21.86115, 30.59235],
       [ 7.09512, 19.91601, 30.55461],
       [ 6.21639, 22.11921, 29.86407],
       [ 9.54567, 21.10023, 31.17834],
       [ 8.72763, 22.9143 , 30.40977],
       [ 8.09217, 19.15203, 31.14315],
       [ 6.1455 , 19.45293, 30.31338],
       [ 6.40509, 22.99131, 28.78746],
       [ 4.97046, 22.0269 , 30.49392],
       [ 9.30291, 19.75587, 31.50015],
       [10.48254, 21.58167, 31.42926],
       [ 7.89786, 18.10908, 31.36194],
       [ 5.3244 , 23.6895 , 28.27542],
       [ 7.36848, 23.0724 , 28.29837],
       [ 3.8913 , 22.72968, 29.988  ],
       [ 4.82511, 21.37716, 31.34868],
       [10.27854, 19.0332 , 32.29524],
       [ 4.05093, 23.51916, 28.8405 ],
       [ 5.46924, 24.27804, 27.37884],
       [ 2.91975, 22.58994, 30.44598],
       [10.1133 , 17.74443, 32.69304],
       [11.40666, 19.63347, 32.73894],
       [ 2.87844, 23.93787, 28.08927],
       [11.21031, 17.53584, 33.42795],
       [11.97837, 18.6716

In [69]:
poly.numbers

array([ 6,  6,  6,  6,  6,  1,  6,  1,  6,  6,  6,  1,  1,  6,  1,  6,  1,
        6,  6,  1,  1,  7,  7,  6,  6,  6,  8,  8,  6,  6,  6,  6,  6,  6,
        7,  6,  1,  7,  6,  1,  6, 44,  1,  6,  1,  1,  7,  7,  7,  7,  1,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  1,  6,  6,  1,  6,  6,  1,
        6,  6,  1,  6,  6,  1,  6,  6,  1,  6,  6,  1,  6,  6,  1,  7,  1,
        7,  1,  7,  1,  7,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  1,  6,
        1,  6,  1,  6,  1,  6,  1,  1,  6,  1,  1,  6,  6,  6,  6,  6,  6,
        6,  1,  6,  1,  6,  1,  6,  1,  6,  1,  1,  6,  1,  1,  6,  6,  8,
        8,  8,  8])

In [73]:
poly.charges

AttributeError: 'Atoms' object has no attribute 'charges'

In [65]:
Atoms??

In [25]:
filename = "/home/jyb/decryst/cp_one/ligand_two_phen-1.xyz"
poly = read("/home/jyb/decryst/cp_one/ligand_two_phen-1.xyz")

KeyError: 'Ru3+'

In [62]:
dir(poly)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ase_handles_dynamic_stress',
 '_calc',
 '_celldisp',
 '_cellobj',
 '_centering_as_array',
 '_constraints',
 '_del_constraints',
 '_get_atomic_numbers',
 '_get_constraints',
 '_get_positions',
 '_masked_rotate',
 '_pbc',
 '_set_positions',
 'append',
 'arrays',
 'ase_objtype',
 'calc',
 'cell',
 'center',
 'constraints',
 'copy',
 'edit',
 'euler_rotate',
 'extend',
 'fromdict',
 'get_all_distances',
 'get_angle',
 'get_angles',
 'get_angular_momentum',
 'get_array',
 'get_atomic_numbers',
 'get_calculator',
 'get_c

In [63]:
getattr(poly)

TypeError: getattr expected at least 2 arguments, got 1

In [11]:
poly.get_positions()

array([[ 7.30983, 21.2823 , 30.32205],
       [ 8.55066, 21.86115, 30.59235],
       [ 7.09512, 19.91601, 30.55461],
       [ 6.21639, 22.11921, 29.86407],
       [ 9.54567, 21.10023, 31.17834],
       [ 8.72763, 22.9143 , 30.40977],
       [ 8.09217, 19.15203, 31.14315],
       [ 6.1455 , 19.45293, 30.31338],
       [ 6.40509, 22.99131, 28.78746],
       [ 4.97046, 22.0269 , 30.49392],
       [ 9.30291, 19.75587, 31.50015],
       [10.48254, 21.58167, 31.42926],
       [ 7.89786, 18.10908, 31.36194],
       [ 5.3244 , 23.6895 , 28.27542],
       [ 7.36848, 23.0724 , 28.29837],
       [ 3.8913 , 22.72968, 29.988  ],
       [ 4.82511, 21.37716, 31.34868],
       [10.27854, 19.0332 , 32.29524],
       [ 4.05093, 23.51916, 28.8405 ],
       [ 5.46924, 24.27804, 27.37884],
       [ 2.91975, 22.58994, 30.44598],
       [10.1133 , 17.74443, 32.69304],
       [11.40666, 19.63347, 32.73894],
       [ 2.87844, 23.93787, 28.08927],
       [11.21031, 17.53584, 33.42795],
       [11.97837, 18.6716

In [59]:
for i in lattices: print(i)

Atom('S', [0.0, 0.0, 0.0], index=0)


In [56]:
filename = "/home/jyb/decryst/cp_one/train.xyz"
lattices = read("/home/jyb/decryst/cp_one/train.xyz",format='extxyz')

In [58]:
lattices

Atoms(symbols='S', pbc=False, cell=[100.0, 100.0, 100.0], calculator=SinglePointCalculator(...))

In [17]:
poly.get_chemical_symbols()

['C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'H',
 'C',
 'C',
 'C',
 'H',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'C',
 'H',
 'H',
 'N',
 'N',
 'C',
 'C',
 'C',
 'O',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'H',
 'N',
 'C',
 'H',
 'C',
 'Ru',
 'H',
 'C',
 'H',
 'H',
 'N',
 'N',
 'N',
 'N',
 'H',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'N',
 'H',
 'N',
 'H',
 'N',
 'H',
 'N',
 'H',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'H',
 'C',
 'H',
 'H',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'H',
 'C',
 'H',
 'H',
 'C',
 'C',
 'O',
 'O',
 'O',
 'O']

In [50]:
list(poly)

[Atom('C', [7.30983, 21.2823, 30.32205], charge=3.0, index=0),
 Atom('C', [8.55066, 21.86115, 30.59235], charge=0.0, index=1),
 Atom('C', [7.09512, 19.91601, 30.55461], charge=0.0, index=2),
 Atom('C', [6.21639, 22.11921, 29.86407], charge=0.0, index=3),
 Atom('C', [9.54567, 21.10023, 31.17834], charge=0.0, index=4),
 Atom('H', [8.72763, 22.9143, 30.40977], charge=0.0, index=5),
 Atom('C', [8.09217, 19.15203, 31.14315], charge=0.0, index=6),
 Atom('H', [6.1455, 19.45293, 30.31338], charge=0.0, index=7),
 Atom('C', [6.40509, 22.99131, 28.78746], charge=0.0, index=8),
 Atom('C', [4.97046, 22.0269, 30.49392], charge=0.0, index=9),
 Atom('C', [9.30291, 19.75587, 31.50015], charge=0.0, index=10),
 Atom('H', [10.48254, 21.58167, 31.42926], charge=0.0, index=11),
 Atom('H', [7.89786, 18.10908, 31.36194], charge=0.0, index=12),
 Atom('C', [5.3244, 23.6895, 28.27542], charge=0.0, index=13),
 Atom('H', [7.36848, 23.0724, 28.29837], charge=0.0, index=14),
 Atom('C', [3.8913, 22.72968, 29.988], ch

In [43]:
from ase import Atom

In [44]:
Atom

In [18]:
dict_all = dict(zip(poly.get_chemical_symbols(),poly.get_positions()))

In [19]:
dict_all

{'C': array([23.93787, 22.91073, 48.12156]),
 'H': array([22.58994, 20.55402, 48.08025]),
 'N': array([19.63347, 18.26106, 39.59334]),
 'O': array([24.77223, 23.90676, 47.94255]),
 'Ru': array([15.49482, 15.49482, 35.50518])}

In [21]:
poly

Atoms(symbols='C78H42N12O6Ru', pbc=False)

In [24]:
lattices.get_chemical_symbols()

['S']

In [26]:
lattices.get_charges()

PropertyNotImplementedError: The property "charges" is not available.

In [28]:
lattices.get_cell()

IndexError: Index out of range.

In [29]:
lattices

Atoms(symbols='S', pbc=False, cell=[100.0, 100.0, 100.0], calculator=SinglePointCalculator(...))

In [32]:
from ase.visualize import view

In [35]:
view(poly, viewer="ngl")

ModuleNotFoundError: No module named 'nglview'

In [135]:
from ase.io import read, write
filename = "/home/jyb/decryst/cp_one/ligand_two_phen-1.xyz"
poly = read("/home/jyb/decryst/cp_one/ligand_two_phen-1.xyz")

In [136]:
poly.get_chemical_symbols()

['C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'H',
 'C',
 'C',
 'C',
 'H',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'C',
 'H',
 'H',
 'N',
 'N',
 'C',
 'C',
 'C',
 'O',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'H',
 'N',
 'C',
 'H',
 'C',
 'Ru',
 'H',
 'C',
 'H',
 'H',
 'N',
 'N',
 'N',
 'N',
 'H',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'C',
 'C',
 'H',
 'N',
 'H',
 'N',
 'H',
 'N',
 'H',
 'N',
 'H',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'H',
 'C',
 'H',
 'H',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'C',
 'H',
 'H',
 'C',
 'H',
 'H',
 'C',
 'C',
 'O',
 'O',
 'O',
 'O']

In [137]:
poly.get_positions()

array([[ 7.30983, 21.2823 , 30.32205],
       [ 8.55066, 21.86115, 30.59235],
       [ 7.09512, 19.91601, 30.55461],
       [ 6.21639, 22.11921, 29.86407],
       [ 9.54567, 21.10023, 31.17834],
       [ 8.72763, 22.9143 , 30.40977],
       [ 8.09217, 19.15203, 31.14315],
       [ 6.1455 , 19.45293, 30.31338],
       [ 6.40509, 22.99131, 28.78746],
       [ 4.97046, 22.0269 , 30.49392],
       [ 9.30291, 19.75587, 31.50015],
       [10.48254, 21.58167, 31.42926],
       [ 7.89786, 18.10908, 31.36194],
       [ 5.3244 , 23.6895 , 28.27542],
       [ 7.36848, 23.0724 , 28.29837],
       [ 3.8913 , 22.72968, 29.988  ],
       [ 4.82511, 21.37716, 31.34868],
       [10.27854, 19.0332 , 32.29524],
       [ 4.05093, 23.51916, 28.8405 ],
       [ 5.46924, 24.27804, 27.37884],
       [ 2.91975, 22.58994, 30.44598],
       [10.1133 , 17.74443, 32.69304],
       [11.40666, 19.63347, 32.73894],
       [ 2.87844, 23.93787, 28.08927],
       [11.21031, 17.53584, 33.42795],
       [11.97837, 18.6716

In [19]:
sym_new_ls = [i.replace("'",'"') for i in sym_ls]

In [18]:
a = 'asd'
a.replace("'",'"')

'asd'

In [21]:
sym_new_ls

['C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'N',
 'C',
 'C',
 'C',
 'O',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'N',
 'C',
 'C',
 'C',
 'N',
 'N',
 'N',
 'N',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'N',
 'N',
 'N',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'O',
 'O',
 'O']

In [215]:
dict((symbol_ls,coor_ls))

{0: [-8.44305, -7.41591, -12.61638],
 1: [-4.138649999999998, -2.76624, -4.088159999999995],
 2: [-9.27741, -8.411939999999998, -12.437369999999994]}

In [214]:
symbol_ls

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2]

In [201]:
a=b = [1,2,30]
[x-y for x,y in zip(a,b)]

[0, 0, 0]

In [210]:
[[x-y for x,y in zip(ref_coor,ls)] for ls in pos_ls]

[[8.18499, -5.787479999999999, 5.183130000000002],
 [6.94416, -6.366329999999998, 4.912830000000003],
 [8.399700000000001, -4.421189999999999, 4.950570000000003],
 [9.27843, -6.624389999999998, 5.641110000000001],
 [5.949150000000001, -5.605409999999999, 4.326840000000004],
 [7.402650000000001, -3.657209999999999, 4.362030000000004],
 [9.08973, -7.496489999999998, 6.7177200000000035],
 [10.524360000000001, -6.5320800000000006, 5.011260000000004],
 [6.19191, -4.261050000000001, 4.005030000000001],
 [10.17042, -8.194679999999998, 7.229760000000002],
 [11.60352, -7.234859999999998, 5.517180000000003],
 [5.216280000000001, -3.53838, 3.209940000000003],
 [11.44389, -8.024339999999999, 6.664680000000004],
 [5.38152, -2.2496100000000006, 2.8121399999999994],
 [4.08816, -4.138649999999998, 2.7662400000000034],
 [12.616380000000001, -8.44305, 7.415910000000004],
 [4.284510000000001, -2.0410199999999996, 2.07723],
 [3.5164500000000007, -3.1767900000000004, 2.0542800000000057],
 [13.74909, -7.938

In [208]:
pos_ls

['C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'C',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'N',
 'C',
 'C',
 'C',
 'N',
 'N',
 'N',
 'N',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'N',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'O',
 'O',
 'O']

In [207]:
[y for x,y in zip(ref_coor,pos_ls[0])]

['C']

In [191]:
elem_dic

{'C': 0, 'N': 1, 'O': 2}

In [182]:
sym_ls

['C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'N',
 'C',
 'C',
 'C',
 'O',
 'O',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'C',
 'N',
 'C',
 'C',
 'C',
 'N',
 'N',
 'N',
 'N',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'N',
 'N',
 'N',
 'N',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'O',
 'O',
 'O',
 'O']

In [181]:
[1,2,3] - [3,4,5]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [176]:
sym_ls.remove('H')

In [180]:
len(sym_ls)

96

In [160]:
sym_ls[0] == 'C'

True

In [162]:
'Ru' in sym_ls

True

In [164]:
sym_ls.index('Ru')

41

In [150]:
pos_ls = [list(i) for i in pos_ls]

In [151]:
pos_ls.pop(0)

[7.30983, 21.2823, 30.32205]

In [152]:
pos_ls

[[8.55066, 21.86115, 30.59235],
 [7.09512, 19.91601, 30.55461],
 [6.21639, 22.11921, 29.86407],
 [9.54567, 21.10023, 31.17834],
 [8.72763, 22.9143, 30.40977],
 [8.09217, 19.15203, 31.14315],
 [6.1455, 19.45293, 30.31338],
 [6.40509, 22.99131, 28.78746],
 [4.97046, 22.0269, 30.49392],
 [9.30291, 19.75587, 31.50015],
 [10.48254, 21.58167, 31.42926],
 [7.89786, 18.10908, 31.36194],
 [5.3244, 23.6895, 28.27542],
 [7.36848, 23.0724, 28.29837],
 [3.8913, 22.72968, 29.988],
 [4.82511, 21.37716, 31.34868],
 [10.27854, 19.0332, 32.29524],
 [4.05093, 23.51916, 28.8405],
 [5.46924, 24.27804, 27.37884],
 [2.91975, 22.58994, 30.44598],
 [10.1133, 17.74443, 32.69304],
 [11.40666, 19.63347, 32.73894],
 [2.87844, 23.93787, 28.08927],
 [11.21031, 17.53584, 33.42795],
 [11.97837, 18.67161, 33.4509],
 [1.74573, 23.43297, 28.43097],
 [3.05745, 24.77223, 27.09324],
 [11.63769, 16.34142, 34.01394],
 [13.2243, 18.72057, 34.05066],
 [12.91269, 16.35468, 34.60605],
 [10.92624, 15.13425, 33.966],
 [13.69146, 17